package entita_statiche.funzione;

public enum Funzionalita {
	//cambia sbarra: apre la sbarra se è chiusa, chiude se aperta
	APRI_SBARRA, CHIUDI_SBARRA, CAMBIA_SBARRA,
	ATTIVA_INTERRUTTORE, DISATTIVA_INTERRUTTORE, CAMBIA_INTERRUTTORE,
	ATTIVA_TELETRASPORTO, DISATTIVA_TELETRASPORTO, CAMBIA_TELETRASPORTO,
	ATTIVA_NEMICO, DISATTIVA_NEMICO
}
